TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: ../..
  label_file_path: ../train_rec.txt
  
EvalReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: ../..
  label_file_path: ../dev_rec.txt

TestReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
